import LandingHeader from "@/components/landing-header";
import { GoogleProvider } from "@/providers/GoogleProvider";
import { Twitter } from "lucide-react";
import { Metadata } from "next";
import Link from "next/link";
import React from "react";
import { BsTwitter } from "react-icons/bs";

export const metadata: Metadata = {
  title: "Twitter | Auth",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <GoogleProvider>
      <div className="h-screen w-screen flex flex-col">
        <LandingHeader className="border border-x-0 border-t-0 border-b border-zinc-800" />
        <div className="flex-1">{children}</div>
      </div>
    </GoogleProvider>
  );
}
